// Next & react
import type { Metadata } from 'next'
import { headers } from "next/headers";
import { StrictMode } from 'react'

// Styling
import 'bulma'
import './globals.css'

// UI Components 
import Navbar from '@/components/layout/navbar'
import Footer from '@/components/layout/footer'
import MainBanner from '@/components/sections/banner'

// Cart Context
import { CartProvider } from '@/context/cartContext'

export const metadata: Metadata = {
  title: 'Next.js Store',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const heads = headers()
  const pathname = heads.get('next-url')

  return (
      <StrictMode>
        <html lang="en" className='overscroll-none'>
          <body>
            <CartProvider>
              <Navbar />
                {pathname != null || pathname != '/' ? null : <MainBanner />} 
                <main className='container px-5 py-5 md:py-6'>
                  {children}
                </main>
              <Footer />
            </CartProvider>
          </body>
        </html>
      </StrictMode>
  )
}