import type { Metadata } from 'next'
import 'bulma'
import './globals.css'

import { StrictMode } from 'react';

// UI Components 
import Navbar from '@/components/layout/navbar'
import Footer from '@/components/layout/footer'

import { CartProvider } from '@/context/cartContext'

export const metadata: Metadata = {
  title: 'Next.js Store',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
      <StrictMode>
        <html lang="en" className='overscroll-none'>
          <body>
            <CartProvider>
              <Navbar />
                <main className='container px-5 py-5 md:py-6'>
                  {children}
                </main>
              <Footer />
            </CartProvider>
          </body>
        </html>
      </StrictMode>
  )
}